language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=django==2.2
  - DJANGO=django==3.0
  - DJANGO=django==3.1
install:
  - pip install $DJANGO

script:
  - python runtests.py

branches:
    only:
        - master

jobs:
  exclude:
    - python: "3.5"
      env: DJANGO=django==3.0
    - python: "3.5"
      env: DJANGO=django==3.1
